import type { Metadata } from "next";

import "./globals.css";

import Providers from "./providers";
import ClientHeaderWrapper from "./components/ClientHeaderWrapper";
import ClientFooterWrapper from "./components/ClientFooterWrapper";
import { CartProvider } from "../contexts/CartContext";
import { LocationProvider } from "../contexts/LocationContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>
          <LocationProvider>
            <CartProvider>
              <ClientHeaderWrapper />
              {children}
              <ClientFooterWrapper />
            </CartProvider>
          </LocationProvider>
        </Providers>
      </body>
    </html>
  );
}
